name: Build Debian Package

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - snap/**
      - .github/**
      - docs/**
      - PKGBUILD
      - .SRCINFO
      - LICENSE

env:
  VERSION: 1.3.6

jobs:

  build-windows-package:
    runs-on: windows-2019

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Build clash lib
        shell: bash
        run: |
          python3 ./build-clash-lib.py
      - name: Build Flutter
        run: |
          flutter build windows --release -v
      - name: Package Fclash
        run: |
          iscc .\setup.iss
      - name: Rename Fclash
        shell: bash
        run: |
          pushd ./Output
          mv fclash.exe fclash-${{ env.VERSION }}-x86_64.exe

      - uses: actions/upload-artifact@v2
        with:
          name: fclash-${{ env.VERSION }}-x86_64.exe
          path: ./Output/fclash-${{ env.VERSION }}-x86_64.exe
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: Output/fclash-${{ env.VERSION }}-x86_64.exe
          token: ${{ secrets.GITHUB_TOKEN }}

  build-macos-package:
    runs-on: macos-10.15

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Build macos dmg
        run: |
          brew install create-dmg tree
      - name: Build Flutter
        run: |
          flutter build macos --release -v

      - name: Package dmg
        run: |
          tree ./build/macos/release
          create-dmg  --app-drop-link 600 185 "fclash-${{ env.VERSION}}.dmg" ./build/macos/release/Products/fclash.app

      - uses: actions/upload-artifact@v2
        with:
          name: fclash-${{ env.VERSION}}.dmg
          path: fclash-${{ env.VERSION}}.dmg
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "fclash-${{ env.VERSION}}.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}


  build-debian-package:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.19.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
      - name: Enable Linux Desktop Support
        run: flutter config --enable-linux-desktop
      - name: install dependencies
        run: sudo apt update -y && sudo apt install -y libappindicator3-dev ninja-build build-essential
      - name: build linux debian package
        run: ./build-deb.sh
      - uses: actions/upload-artifact@v2
        with:
          name: cn.kingtous.fclash.deb
          path: ./debian/cn.kingtous.fclash.deb

      - name: Rename deb package
        run: |
          mv ./debian/cn.kingtous.fclash.deb ./debian/cn.kingtous.fclash-${{ env.VERSION }}-x86_64.deb
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          artifacts: "debian/cn.kingtous.fclash.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
